[[Main]]
Name = "博客"
Pre = "list-alt"
URL = "/post/"
Weight = 1

[[Main]]
Name = "编程"
Pre = "wpexplorer"
URL = "/categories/编程/"
Weight = 2

[[Main]]
Name = "翻译"
Pre = "language"
URL = "/categories/翻译/"
Weight = 3

[[Main]]
Name = "随想"
Pre = "bathtub"
URL = "/categories/随想/"
Weight = 4


