[[main]]
name = "博客"
url = "/post/"
weight = 1

[[main]]
name = "编程"
url = "/categories/编程/"
weight = 2

[[main]]
name = "翻译"
url = "/categories/翻译/"
weight = 3

[[main]]
name = "随想"
url = "/categories/随想/"
weight = 4


