# 站点标题等信息
Subtitle = "Captain your own Ship."
Description = "Captain your own Ship."
Keywords = "读书,代码,架构,JVM,Java,Kotlin,Python,Rust"
Imglogo = "/img/logo.png"

# 作者介绍
AuthorName = "zhimoe"
Introduce = "xkcd386, bold&bald, builder"
AuthorImg = "/img/avatar.jpg"

DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"
Fancybox = true

[Statistics]
#revolver_map_id = "55k6ne41ev6"
google_analytics = "G-CJJZFN2DZR" # google站点访问日志，国内不建议开启
cloudflare_worker = "pageview.zhimoe"


# 评论 见themes/next/layout/partials/widgets/comment.html
[Comment]
giscus = "zhimoe.github.io"


# 标签云
[TagsCloud]
Enable = true
Limit = 12


# 社交媒体
[[Socials]]
Name = "GitHub"
Icon = "github"
URL = "https://github.com/zhimoe/"

[[Socials]]
Name = "ZhiHu"
Icon = "globe"
URL = "https://www.zhihu.com/question/21142149/answer/52383396"


# 友情链接
[[Links]]
Name = "可视化Git"
Permalink = "https://learngitbranching.js.org/"

[[Links]]
Name = "绘画博物馆"
Permalink = "https://gallerix.asia/"

[[Links]]
Name = "Rust小抄"
Permalink = "https://cheats.rs/"

[[Links]]
Name = "谷歌机器学习"
Permalink = "https://developers.google.com/machine-learning/crash-course/"

