ArticleDecContent = "本博客文章除特别声明外，均采用 <a href='https://creativecommons.org/licenses/by-nc-sa/3.0/' target='_blank' style='text-decoration: underline;'>CC BY-NC-SA 3.0</a>许可协议，转载请注明出处！"

# 站点标题等信息
Subtitle = "the craft of programming"
Description = "编程是一门手艺"
Keywords =  "读书,代码,架构,JVM,Java,Scala,Python,Clojure,Rust"
Imglogo = "/img/logo.png"
Domain = "https://zhi.moe"

AuthorName = "zhimoe"
Introduce = "Captain your own Ship."
AuthorImg = "/img/avatar.png"

DateFormat = "2006-01-02"
YearFormat = "2006年"
MonthFormat = "01-02"
Fancybox = true

[Statistics]
  # RevolverMapId = "55k6ne41ev6"
  # BusuanziCounter = ""
  # CNNZSiteId = ""
  # BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  GoogleAnalytics = "UA-137200637-1" # google站点访问日志，国内不建议开启

[Author]
  Name = "zhimoe"

# Disqus评论 见themes/next/layout/partials/widgets/comment.html
[Comment]
  Disqus = "zhimoe"

[TagsCloud]
  Enable = true
  Limit = 10

# 社交媒体
[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/zhimoe/"

[[Socials]]
  Name = "ZhiHu"
  Icon = "globe"
  URL = "https://www.zhihu.com/question/21142149/answer/52383396"

# 友情链接
[[Links]]
    Name = "可视化学习Git"
    Permalink = "https://learngitbranching.js.org/"

[[Links]]
    Name = "美团技术团队"
    Permalink = "https://tech.meituan.com/"

[[Links]]
    Name = "艺术绘画"
    Permalink = "https://gallerix.asia/"

[[Links]]
    Name = "500px"
    Permalink = "https://500px.com/"

[[Links]]
    Name = "RustCheatsheet"
    Permalink = "https://cheats.rs/"

[[Links]]
    Name = "谷歌机器学习课程"
    Permalink = "https://developers.google.com/machine-learning/crash-course/"

