description = "Captain your own Ship."
footer = "[xdh](https://zhi.moe) &copy; {Year}"

[logo.en]
alt = "香取海"

[statistics]
google_analytics = "G-CJJZFN2DZR" # google 站点访问日志，国内不建议开启
cloudflare_worker = "pageview.zhimoe"

